#!/usr/bin/env python3
"""Otter pass/fail grader — shared verifier harness. Do not edit this file.

Second of the two standardized verifier scripts invoked by tests/test.sh:

    tests/rubric_score.py — runs checks.py once, computes the Rubric Score
    tests/pass_fail.py    — computes the final Pass/Fail Grade

This script does NOT re-run the task checks. It reads the criteria and
metric values that rubric_score.py wrote to <logs>/rubric_result.json,
then:

  1. Compares the agent's metrics against the human-derived thresholds
     in human_scores.json under "pass_criteria".
  2. Generates the final "pass/fail" milestone automatically — one
     criterion per pass_criteria metric. You should never declare this
     milestone in milestones_and_rubrics.json and never write checks.py
     code for it; pass_criteria is its single source of truth.
  3. Computes the Binary Pass/Fail Grade:
         1 if every critical intermediate milestone passes AND every
         primary metric meets its human-derived threshold, else 0.
     A milestone passes when its score is 1.0. Milestones are critical
     by default; set "critical": false in milestones_and_rubrics.json
     for milestones that should only affect the Rubric Score.
  4. Writes the final result.json, criteria.json, reward.json, and
     reward.txt that Harbor reads.
"""

from __future__ import annotations

import json
import traceback
from dataclasses import asdict
from pathlib import Path
from typing import Any

from rubric_score import (
    RUBRIC_RESULT_FILENAME,
    EvalPaths,
    discover_paths,
)

# Milestone id used for the auto-generated final pass/fail milestone.
FINAL_MILESTONE_ID = "final-pass-fail"


# ---------------------------------------------------------------------------
# Comparison operators for primary metrics
# ---------------------------------------------------------------------------

_COMPARISONS: dict[str, tuple[str, Any]] = {
    "gte": (">=", lambda actual, threshold: actual >= threshold),
    "gt":  (">",  lambda actual, threshold: actual > threshold),
    "lte": ("<=", lambda actual, threshold: actual <= threshold),
    "lt":  ("<",  lambda actual, threshold: actual < threshold),
    "eq":  ("==", lambda actual, threshold: actual == threshold),
}


def evaluate_primary_metrics(
    agent_metrics: dict[str, Any],
    human_scores: dict[str, Any],
) -> list[dict[str, Any]]:
    """Compare agent metrics against thresholds from human_scores.json.

    pass_criteria values can be either:
      - A number: threshold with default comparison ">=" (higher is better)
      - An object: {"threshold": 0.5, "comparison": "lte"} for explicit
        control over comparison direction.

    Supported comparisons: gte (>=), gt (>), lte (<=), lt (<), eq (==).

    Returns a list of metric result dicts. Empty list if no pass_criteria
    are defined.
    """
    pass_criteria = human_scores.get("pass_criteria", {})
    if not pass_criteria:
        return []

    results: list[dict[str, Any]] = []

    for key, spec in pass_criteria.items():
        # Parse threshold and comparison from the spec.
        # Simple form: "auroc": 0.80  (implies >=)
        # Object form: "loss": {"threshold": 0.5, "comparison": "lte"}
        if isinstance(spec, dict):
            threshold = float(spec["threshold"])
            comparison = spec.get("comparison", "gte")
        else:
            threshold = float(spec)
            comparison = "gte"

        if comparison not in _COMPARISONS:
            results.append({
                "key": key,
                "passed": False,
                "threshold": threshold,
                "comparison": comparison,
                "error": f"Unknown comparison {comparison!r} for metric "
                         f"{key!r}. Valid: {sorted(_COMPARISONS)}",
            })
            continue

        symbol, compare_fn = _COMPARISONS[comparison]

        if key not in agent_metrics:
            results.append({
                "key": key,
                "passed": False,
                "threshold": threshold,
                "comparison": symbol,
                "error": f"Metric {key!r} not returned by checks.py. "
                         f"Found: {sorted(agent_metrics)}",
            })
            continue

        actual = float(agent_metrics[key])
        passed = compare_fn(actual, threshold)
        results.append({
            "key": key,
            "passed": passed,
            "value": actual,
            "threshold": threshold,
            "comparison": symbol,
        })

    return results


def validate_pass_fail_config(
    agent_metrics: dict[str, Any],
    human_scores: dict[str, Any],
) -> None:
    """Validate human_scores.json against metrics from checks.py.

    Raises ValueError on any mismatch so ECs catch config errors
    immediately rather than getting silent fallback behavior.
    """
    errors: list[str] = []

    pass_criteria = human_scores.get("pass_criteria", {})

    if not human_scores:
        errors.append(
            "human_scores.json not found or empty. Every task must "
            "provide tests/human_scores.json with pass_criteria."
        )
    elif not pass_criteria:
        errors.append(
            "human_scores.json has no pass_criteria. The final pass/fail "
            "milestone must validate the agent against human-derived "
            "thresholds — add pass_criteria to human_scores.json."
        )

    if pass_criteria and not agent_metrics:
        errors.append(
            f"human_scores.json defines pass_criteria "
            f"{sorted(pass_criteria)} but checks.py returned no metrics. "
            f"Return a 'metrics' dict from checks.py evaluate()."
        )

    if pass_criteria and agent_metrics:
        missing = sorted(set(pass_criteria) - set(agent_metrics))
        if missing:
            errors.append(
                f"pass_criteria keys {missing} not found in metrics "
                f"returned by checks.py. Found: {sorted(agent_metrics)}."
            )

    if errors:
        raise ValueError(
            "Configuration mismatch between checks.py, "
            "milestones_and_rubrics.json, and/or human_scores.json:\n  - "
            + "\n  - ".join(errors)
        )


def build_final_milestone_criteria(
    primary_metric_results: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Generate the final pass/fail milestone's criteria.

    The milestone is synthesized automatically — one criterion per
    pass_criteria metric — so ECs never declare it in
    milestones_and_rubrics.json.
    """
    criteria: list[dict[str, Any]] = []
    for metric in primary_metric_results:
        criterion: dict[str, Any] = {
            "id": str(metric["key"]),
            "milestone_id": FINAL_MILESTONE_ID,
            "weight": 1.0,
            "passed": bool(metric["passed"]),
            "metric": metric["key"],
            "threshold": metric["threshold"],
            "detail": metric.get(
                "error",
                f"{metric['key']} = {metric.get('value')} "
                f"{metric.get('comparison', '>=')} {metric['threshold']}",
            ),
        }
        if "value" in metric:
            criterion["observed"] = metric["value"]
        criteria.append(criterion)
    return criteria


def compute_grade(
    milestones: list[dict[str, Any]],
    primary_metric_results: list[dict[str, Any]],
) -> float:
    """Binary pass/fail.

    1.0 if ALL of the following hold, else 0.0:
      - Every critical intermediate milestone passes. A milestone
        passes when its score is 1.0 (every positive-weight criterion
        passed, no penalty criterion fired). Milestones default to
        critical=true when the flag is omitted.
      - Every primary metric meets its human-derived threshold (the
        final pass/fail milestone)

    Returns 0.0 if there are no milestones or no primary metrics at all.
    """
    if not milestones:
        return 0.0

    critical = [m for m in milestones if m.get("critical", True)]
    if critical and not all(m.get("passed", False) for m in critical):
        return 0.0

    if not primary_metric_results:
        return 0.0
    if not all(m["passed"] for m in primary_metric_results):
        return 0.0

    return 1.0


def write_outputs(result: dict[str, Any], logs_dir: Path) -> None:
    logs_dir.mkdir(parents=True, exist_ok=True)

    (logs_dir / "result.json").write_text(
        json.dumps(result, indent=2, sort_keys=True), encoding="utf-8"
    )
    (logs_dir / "criteria.json").write_text(
        json.dumps(result.get("criteria", []), indent=2, sort_keys=True),
        encoding="utf-8",
    )
    # reward.json must only contain scalar values (numbers/bools).
    # Harbor validates this with Pydantic. milestone_scores and
    # primary_metrics are dicts/lists, so they go in result.json only.
    reward_payload = {
        "reward": float(result.get("reward", 0.0)),
        "rubric_score": float(result.get("rubric_score", 0.0)),
        "passed": bool(result.get("passed", False)),
    }
    (logs_dir / "reward.json").write_text(
        json.dumps(reward_payload, indent=2, sort_keys=True), encoding="utf-8"
    )
    (logs_dir / "reward.txt").write_text(
        f"{reward_payload['reward']:.12g}\n", encoding="utf-8"
    )

    print(json.dumps(result, indent=2, sort_keys=True))


def error_result(
    message: str, paths: EvalPaths | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "reward": 0.0,
        "rubric_score": 0.0,
        "milestone_scores": {},
        "milestones": [],
        "primary_metrics": [],
        "passed": False,
        "error": message,
        "criteria": [{
            "id": "verifier_execution",
            "passed": False,
            "weight": 1.0,
            "detail": message,
        }],
        "metadata": {},
    }
    if paths is not None:
        result["paths"] = asdict(paths)
    return result


def main() -> int:
    paths = discover_paths()

    try:
        # Read what rubric_score.py produced — checks run exactly once.
        rubric_result_path = Path(paths.logs_dir) / RUBRIC_RESULT_FILENAME
        if not rubric_result_path.exists():
            raise FileNotFoundError(
                f"{rubric_result_path} not found. tests/test.sh must run "
                f"rubric_score.py before pass_fail.py."
            )
        with rubric_result_path.open("r", encoding="utf-8") as fh:
            rubric_result = json.load(fh)

        # A hard failure in rubric_score.py (checks crashed, config
        # mismatch) means the task cannot pass — propagate the error.
        if rubric_result.get("error"):
            raise RuntimeError(
                f"rubric_score.py failed: {rubric_result['error']}"
            )

        deterministic_criteria = rubric_result.get("criteria", [])
        milestone_meta = rubric_result.get("milestones", [])
        agent_metrics = rubric_result.get("metrics", {})
        if not isinstance(agent_metrics, dict):
            agent_metrics = {}

        # Load human scores (thresholds for primary metrics).
        human_scores: dict[str, Any] = {}
        if paths.human_scores_path:
            with Path(paths.human_scores_path).open(
                "r", encoding="utf-8"
            ) as fh:
                human_scores = json.load(fh)

        validate_pass_fail_config(agent_metrics, human_scores)

        primary_metric_results = evaluate_primary_metrics(
            agent_metrics, human_scores,
        )

        final_criteria = build_final_milestone_criteria(
            primary_metric_results,
        )
        final_milestone_id = FINAL_MILESTONE_ID
        final_milestone_passed = bool(final_criteria) and all(
            c["passed"] for c in final_criteria
        )

        grade = compute_grade(milestone_meta, primary_metric_results)

        milestone_scores = dict(rubric_result.get("milestone_scores", {}))
        milestone_scores[final_milestone_id] = (
            1.0 if final_milestone_passed else 0.0
        )
        milestones = list(milestone_meta) + [{
            "id": final_milestone_id,
            "critical": True,
            "score": 1.0 if final_milestone_passed else 0.0,
            "passed": final_milestone_passed,
        }]

        result = {
            "reward": max(0.0, min(1.0, grade)),
            "rubric_score": max(
                0.0, min(1.0, float(rubric_result.get("rubric_score", 0.0)))
            ),
            "milestone_scores": milestone_scores,
            "milestones": milestones,
            "primary_metrics": primary_metric_results,
            "passed": grade == 1.0,
            "criteria": list(deterministic_criteria) + final_criteria,
            "metadata": rubric_result.get("metadata", {}),
            "paths": asdict(paths),
        }
    except Exception as exc:  # noqa: BLE001 — verifier must always emit a result
        result = error_result(f"{type(exc).__name__}: {exc}", paths)
        result["traceback"] = traceback.format_exc()

    write_outputs(result, Path(paths.logs_dir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
