#!/usr/bin/env python3
"""Otter rubric scorer — shared verifier harness. Do not edit this file.

First of the two standardized verifier scripts invoked by tests/test.sh:

    tests/rubric_score.py — runs checks.py once, computes the Rubric Score
    tests/pass_fail.py    — computes the final Pass/Fail Grade

Task-specific checks belong in checks.py, which must expose:

    def evaluate(context: dict) -> dict:
        return {
            "criteria": [
                {"id": "...", "passed": True, "detail": "..."},
            ],
            "metrics": {"auroc": 0.85, ...},
        }

Criterion weights and milestone critical flags come from
milestones_and_rubrics.json, NOT from checks.py.

This script runs the task checks exactly once and computes:

    Per-Milestone Scores — weighted sum per milestone, 0 to 1 (diagnostic)
    Overall Rubric Score — weighted sum of all deterministic criteria,
                           0 to 1 (diagnostic)

All scores are clamped to the [0, 1] range before being written —
a negative score is never emitted; anything below 0 is reported as 0.

Everything pass_fail.py needs (criteria results, metrics, scores) is
written to <logs>/rubric_result.json so the checks never run twice.

The final "pass/fail" milestone is NOT declared in
milestones_and_rubrics.json and has no checks in checks.py —
pass_fail.py generates it automatically from the pass_criteria
thresholds in human_scores.json and computes the binary grade.
"""

from __future__ import annotations

import importlib.util
import json
import os
import sys
import traceback
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

# Reserved milestone type. The final pass/fail milestone is generated
# automatically by pass_fail.py from human_scores.json pass_criteria;
# declaring it in milestones_and_rubrics.json is a config error.
FINAL_MILESTONE_TYPE = "final_pass_fail"

# Name of the intermediate file this script writes and pass_fail.py reads.
RUBRIC_RESULT_FILENAME = "rubric_result.json"


def clamp_score(value: float) -> float:
    """Clamp a score to [0, 1]. Negative scores are never written."""
    return max(0.0, min(1.0, float(value)))


@dataclass(frozen=True)
class EvalPaths:
    workdir: str
    output_dir: str
    tests_dir: str
    logs_dir: str
    task_dir: str | None
    human_scores_path: str | None
    rubrics_path: str | None


def _path_from_env(name: str, fallback: Path | None = None) -> Path | None:
    value = os.environ.get(name)
    if value:
        return Path(value)
    return fallback


def discover_paths() -> EvalPaths:
    tests_dir = _path_from_env("OTTER_TESTS_DIR", Path("/tests"))
    if tests_dir is None or not tests_dir.exists():
        tests_dir = Path(__file__).resolve().parent

    default_workdir = Path("/app") if Path("/app").exists() else Path.cwd()
    workdir = _path_from_env(
        "FINAL_WORKDIR", _path_from_env("HARBOR_WORKDIR", default_workdir)
    )
    assert workdir is not None

    output_dir = _path_from_env("OUTPUT_DIR")
    if output_dir is None:
        preferred = workdir / "output"
        output_dir = preferred if preferred.exists() else workdir / "outputs"

    logs_dir = _path_from_env("OTTER_LOG_DIR", Path("/logs/verifier"))
    assert logs_dir is not None

    task_dir = _path_from_env("TASK_DIR")
    human_scores_path = _path_from_env(
        "HUMAN_SCORES_PATH", tests_dir / "human_scores.json"
    )
    rubrics_path = _path_from_env(
        "OTTER_RUBRICS_PATH", tests_dir / "milestones_and_rubrics.json"
    )

    return EvalPaths(
        workdir=str(workdir),
        output_dir=str(output_dir),
        tests_dir=str(tests_dir),
        logs_dir=str(logs_dir),
        task_dir=str(task_dir) if task_dir else None,
        human_scores_path=(
            str(human_scores_path)
            if human_scores_path and human_scores_path.exists()
            else None
        ),
        rubrics_path=(
            str(rubrics_path)
            if rubrics_path and rubrics_path.exists()
            else None
        ),
    )


def load_checks_module(tests_dir: Path) -> ModuleType:
    candidates = [
        os.environ.get("OTTER_CHECKS_MODULE"),
        str(tests_dir / "checks.py"),
        str(tests_dir / "task_checks.py"),
    ]
    module_path = None
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            module_path = Path(candidate)
            break

    if module_path is None:
        raise FileNotFoundError(
            f"No verifier module found. Tried: "
            f"{[c for c in candidates if c]}. "
            "Each task must provide tests/checks.py with "
            "evaluate(context) -> dict."
        )

    for import_path in (tests_dir, module_path.parent):
        path_str = str(import_path)
        if path_str not in sys.path:
            sys.path.insert(0, path_str)

    spec = importlib.util.spec_from_file_location("checks", module_path)
    if spec is None or spec.loader is None:
        raise ImportError(
            f"Could not import verifier module: {module_path}"
        )
    module = importlib.util.module_from_spec(spec)
    sys.modules["checks"] = module
    spec.loader.exec_module(module)
    return module


def split_milestones(
    rubrics: dict[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Split milestones into (deterministic, final_pass_fail) lists."""
    deterministic: list[dict[str, Any]] = []
    final: list[dict[str, Any]] = []
    for milestone in rubrics.get("milestones", []):
        if milestone.get("type") == FINAL_MILESTONE_TYPE:
            final.append(milestone)
        else:
            deterministic.append(milestone)
    return deterministic, final


def build_rubric_lookup(
    milestones: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    """Build a criterion_id -> {weight} lookup.

    milestones_and_rubrics.json is the single source of truth for
    criterion weights.
    """
    lookup: dict[str, dict[str, Any]] = {}
    for milestone in milestones:
        for criterion in milestone.get("criteria", []):
            cid = criterion.get("id", "")
            lookup[cid] = {
                "weight": float(criterion.get("weight", 1.0)),
            }
    return lookup


def normalize_criterion(
    raw: dict[str, Any],
    index: int,
    rubric_lookup: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    cid = raw.get("id") or raw.get("name") or f"criterion_{index:03d}"
    cid_str = str(cid)

    # Weight comes from milestones_and_rubrics.json. Fall back to
    # checks.py values only if the criterion is missing from the
    # rubrics (shouldn't happen in a well-formed task).
    rubric = rubric_lookup.get(cid_str, {})
    weight = float(rubric.get("weight", raw.get("weight", 1.0)))

    normalized: dict[str, Any] = {
        "id": cid_str,
        "passed": bool(raw.get("passed", raw.get("ok", False))),
        "weight": weight,
    }
    for key in (
        "milestone_id", "description", "detail",
        "actual", "expected", "metric", "threshold", "observed",
        "artifact",
    ):
        if key in raw:
            normalized[key] = raw[key]
    return normalized


def compute_rubric_score(criteria: list[dict[str, Any]]) -> float:
    """Weighted sum of passing criteria, clamped to [0, 1].

    Negative-weight (penalty) criteria can drive the raw weighted sum
    below zero; the result is clamped so a negative score is never
    returned or written.
    """
    total = sum(max(float(c["weight"]), 0.0) for c in criteria)
    if total <= 0:
        return 0.0
    earned = sum(
        float(c["weight"]) for c in criteria
        if (float(c["weight"]) >= 0 and c["passed"])
        or (float(c["weight"]) < 0 and not c["passed"])
    )
    return clamp_score(earned / total)


def compute_milestone_scores(
    criteria: list[dict[str, Any]],
) -> dict[str, float]:
    """Weighted sum per milestone, keyed by milestone_id.

    Each per-milestone score is clamped to [0, 1] — never negative.
    """
    by_milestone: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for c in criteria:
        mid = str(c.get("milestone_id", "uncategorized"))
        by_milestone[mid].append(c)
    return {
        mid: clamp_score(compute_rubric_score(milestone_criteria))
        for mid, milestone_criteria in by_milestone.items()
    }


def build_milestone_meta(
    milestones: list[dict[str, Any]],
    milestone_scores: dict[str, float],
) -> list[dict[str, Any]]:
    """Per-milestone summary: score, pass status, and critical flag.

    A milestone passes when its score is 1.0 — every positive-weight
    criterion passed and no negative-weight (penalty) criterion fired.
    Critical milestones (the default when the flag is omitted) gate the
    Pass/Fail Grade in pass_fail.py; non-critical milestones only
    affect the Rubric Score. Scores are clamped to [0, 1] — never
    negative.
    """
    meta: list[dict[str, Any]] = []
    for milestone in milestones:
        mid = str(milestone.get("id", ""))
        score = clamp_score(milestone_scores.get(mid, 0.0))
        meta.append({
            "id": mid,
            "critical": bool(milestone.get("critical", True)),
            "score": score,
            "passed": score == 1.0,
        })
    return meta


def validate_rubric_config(
    raw_criteria: list[dict[str, Any]],
    deterministic_milestones: list[dict[str, Any]],
    final_milestones: list[dict[str, Any]],
) -> None:
    """Validate checks.py output against milestones_and_rubrics.json.

    Raises ValueError on any mismatch so ECs catch config errors
    immediately rather than getting silent fallback behavior.

    Metric/pass_criteria validation happens in pass_fail.py.
    """
    errors: list[str] = []

    # Spec shape: at least 2 deterministic (intermediate) milestones.
    # The final pass/fail milestone is generated automatically by
    # pass_fail.py and must NOT be declared in the rubrics JSON.
    if len(deterministic_milestones) < 2:
        errors.append(
            f"milestones_and_rubrics.json must define at least 2 "
            f"intermediate (deterministic) milestones; found "
            f"{len(deterministic_milestones)}."
        )
    if final_milestones:
        errors.append(
            f"milestones_and_rubrics.json declares "
            f"{len(final_milestones)} milestone(s) with type "
            f"{FINAL_MILESTONE_TYPE!r}. The final pass/fail milestone "
            f"is generated automatically by pass_fail.py from "
            f"human_scores.json pass_criteria — remove it from the "
            f"JSON."
        )
    for milestone in deterministic_milestones:
        if not milestone.get("criteria"):
            errors.append(
                f"Milestone {milestone.get('id', '?')!r} defines no "
                f"criteria; every deterministic milestone needs at "
                f"least 1."
            )

    rubric_criterion_ids: set[str] = set()
    rubric_milestone_ids: set[str] = set()
    for milestone in deterministic_milestones:
        mid = milestone.get("id", "")
        if mid:
            rubric_milestone_ids.add(mid)
        for criterion in milestone.get("criteria", []):
            cid = criterion.get("id", "")
            if cid:
                rubric_criterion_ids.add(cid)

    checks_criterion_ids: set[str] = set()
    checks_milestone_ids: set[str] = set()
    for c in raw_criteria:
        cid = str(c.get("id") or c.get("name") or "")
        mid = str(c.get("milestone_id") or "")
        if cid:
            checks_criterion_ids.add(cid)
        if mid:
            checks_milestone_ids.add(mid)

    # Criterion IDs in checks.py but not in rubrics.
    unknown_criteria = sorted(checks_criterion_ids - rubric_criterion_ids)
    if unknown_criteria:
        errors.append(
            f"Criterion IDs {unknown_criteria} in checks.py not found in "
            f"milestones_and_rubrics.json. Expected: "
            f"{sorted(rubric_criterion_ids)}"
        )

    # Criterion IDs in rubrics but not in checks.py.
    missing_criteria = sorted(rubric_criterion_ids - checks_criterion_ids)
    if missing_criteria:
        errors.append(
            f"Criterion IDs {missing_criteria} in "
            f"milestones_and_rubrics.json have no matching check in "
            f"checks.py. Expected: {sorted(checks_criterion_ids)}"
        )

    # Milestone IDs in checks.py but not in rubrics.
    unknown_milestones = sorted(
        checks_milestone_ids - rubric_milestone_ids
    )
    if unknown_milestones:
        errors.append(
            f"Milestone IDs {unknown_milestones} in checks.py not found in "
            f"milestones_and_rubrics.json. Expected: "
            f"{sorted(rubric_milestone_ids)}"
        )

    if errors:
        raise ValueError(
            "Configuration mismatch between checks.py and "
            "milestones_and_rubrics.json:\n  - "
            + "\n  - ".join(errors)
        )


def write_rubric_result(result: dict[str, Any], logs_dir: Path) -> None:
    logs_dir.mkdir(parents=True, exist_ok=True)
    (logs_dir / RUBRIC_RESULT_FILENAME).write_text(
        json.dumps(result, indent=2, sort_keys=True), encoding="utf-8"
    )
    print(json.dumps(result, indent=2, sort_keys=True))


def error_rubric_result(
    message: str, paths: EvalPaths | None = None,
) -> dict[str, Any]:
    result: dict[str, Any] = {
        "rubric_score": 0.0,
        "milestone_scores": {},
        "milestones": [],
        "metrics": {},
        "error": message,
        "criteria": [{
            "id": "verifier_execution",
            "passed": False,
            "weight": 1.0,
            "detail": message,
        }],
        "metadata": {},
    }
    if paths is not None:
        result["paths"] = asdict(paths)
    return result


def main() -> int:
    paths = discover_paths()
    context: dict[str, Any] = {
        "paths": asdict(paths),
        "workdir": Path(paths.workdir),
        "output_dir": Path(paths.output_dir),
        "tests_dir": Path(paths.tests_dir),
        "logs_dir": Path(paths.logs_dir),
        "env": dict(os.environ),
    }

    try:
        # Load milestones and rubrics (weights and critical flags).
        if not paths.rubrics_path:
            raise FileNotFoundError(
                "milestones_and_rubrics.json not found. Every task must "
                "provide tests/milestones_and_rubrics.json."
            )
        with Path(paths.rubrics_path).open("r", encoding="utf-8") as fh:
            rubrics = json.load(fh)

        deterministic_milestones, final_milestones = split_milestones(rubrics)
        rubric_lookup = build_rubric_lookup(deterministic_milestones)

        # Run task-specific checks — exactly once. pass_fail.py reads
        # the results from rubric_result.json instead of re-running.
        module = load_checks_module(Path(paths.tests_dir))
        if hasattr(module, "evaluate"):
            raw = module.evaluate(context)
        elif hasattr(module, "build_criteria"):
            raw = {"criteria": module.build_criteria(context)}
        else:
            raise AttributeError(
                "checks.py must define evaluate(context) or "
                "build_criteria(context)"
            )
        if isinstance(raw, list):
            raw = {"criteria": raw}
        if not isinstance(raw, dict):
            raise TypeError(
                "Verifier returned neither a dict nor a list of criteria"
            )

        raw_criteria = raw.get("criteria", [])
        if not isinstance(raw_criteria, list):
            raise TypeError("result['criteria'] must be a list")

        agent_metrics = raw.get("metrics", {})
        if not isinstance(agent_metrics, dict):
            agent_metrics = {}

        # Validate IDs are consistent across checks.py and the rubrics.
        validate_rubric_config(
            raw_criteria, deterministic_milestones, final_milestones,
        )

        criteria = [
            normalize_criterion(c, i, rubric_lookup)
            for i, c in enumerate(raw_criteria, start=1)
            if isinstance(c, dict)
        ]

        milestone_scores = compute_milestone_scores(criteria)
        result = {
            "rubric_score": clamp_score(compute_rubric_score(criteria)),
            "milestone_scores": milestone_scores,
            "milestones": build_milestone_meta(
                deterministic_milestones, milestone_scores,
            ),
            "metrics": agent_metrics,
            "criteria": criteria,
            "metadata": raw.get("metadata", {}),
            "paths": asdict(paths),
        }
    except Exception as exc:  # noqa: BLE001 — verifier must always emit a result
        result = error_rubric_result(f"{type(exc).__name__}: {exc}", paths)
        result["traceback"] = traceback.format_exc()

    write_rubric_result(result, Path(paths.logs_dir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
