#!/usr/bin/env bash
set -uo pipefail

# Standard Harbor verifier entrypoint. Do not edit this file.
#
# Invokes the two standardized scoring scripts, in order:
#   1. rubric_score.py — runs checks.py once, computes the Rubric Score
#   2. pass_fail.py    — computes the final Pass/Fail Grade and writes
#                        reward.json / reward.txt for Harbor

LOG_DIR="${OTTER_LOG_DIR:-/logs/verifier}"
mkdir -p "${LOG_DIR}"

PYTHON_BIN="${PYTHON:-python3}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUBRIC_SCORE_PY="${OTTER_RUBRIC_SCORE_PY:-/tests/rubric_score.py}"
if [[ ! -f "${RUBRIC_SCORE_PY}" ]]; then
  RUBRIC_SCORE_PY="${SCRIPT_DIR}/rubric_score.py"
fi

PASS_FAIL_PY="${OTTER_PASS_FAIL_PY:-/tests/pass_fail.py}"
if [[ ! -f "${PASS_FAIL_PY}" ]]; then
  PASS_FAIL_PY="${SCRIPT_DIR}/pass_fail.py"
fi

"${PYTHON_BIN}" "${RUBRIC_SCORE_PY}"
rubric_status=$?

# pass_fail.py always runs so a reward is always produced; it reads
# rubric_score.py's output (including any error) from rubric_result.json.
"${PYTHON_BIN}" "${PASS_FAIL_PY}"
pass_fail_status=$?

if [[ ! -f "${LOG_DIR}/reward.txt" ]]; then
  echo 0 > "${LOG_DIR}/reward.txt"
fi

if [[ ${rubric_status} -ne 0 ]]; then
  exit "${rubric_status}"
fi
exit "${pass_fail_status}"
